In [28]:
from __future__ import print_function
import torch
import numpy as np

## initialize

In [7]:
x = torch.empty(5, 3)
x = torch.rand(5, 3)
x = torch.zeros(5, 3, dtype=torch.long)
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5, 3, dtype=torch.double)   # new_* methods take in sizes
print(x)

#x = torch.randn_like(x, dtype=torch.float) # override dtype!
#print(x)                                   # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x.size()

torch.Size([5, 3])

## operation

In [14]:
y = torch.rand(5, 3)
print(x + y)
torch.add(x, y)

tensor([[1.9538, 1.7406, 1.7930],
        [1.0640, 1.6394, 1.5219],
        [1.9530, 1.8089, 1.4606],
        [1.4783, 1.2519, 1.3943],
        [1.6493, 1.3084, 1.7689]], dtype=torch.float64)


tensor([[1.9538, 1.7406, 1.7930],
        [1.0640, 1.6394, 1.5219],
        [1.9530, 1.8089, 1.4606],
        [1.4783, 1.2519, 1.3943],
        [1.6493, 1.3084, 1.7689]], dtype=torch.float64)

In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.9538, 1.7406, 1.7930],
        [1.0640, 1.6394, 1.5219],
        [1.9530, 1.8089, 1.4606],
        [1.4783, 1.2519, 1.3943],
        [1.6493, 1.3084, 1.7689]])


In [17]:
# adds x to y
y.add_(x)
print(y)

tensor([[1.9538, 1.7406, 1.7930],
        [1.0640, 1.6394, 1.5219],
        [1.9530, 1.8089, 1.4606],
        [1.4783, 1.2519, 1.3943],
        [1.6493, 1.3084, 1.7689]])


In [22]:
y[0, :]

tensor([1.9538, 1.7406, 1.7930])

In [25]:
y.view(3, -1)

tensor([[1.9538, 1.7406, 1.7930, 1.0640, 1.6394],
        [1.5219, 1.9530, 1.8089, 1.4606, 1.4783],
        [1.2519, 1.3943, 1.6493, 1.3084, 1.7689]])

## NumPy Bridge

In [31]:
a = torch.ones(5)
a = a.numpy()
print(a)
a + 1

[1. 1. 1. 1. 1.]


array([2., 2., 2., 2., 2.], dtype=float32)

In [32]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [34]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float64)
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
